/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-01-05 08:17:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class MyJsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<style>\r\n");
      out.write(".slider {\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("\twidth: 828px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider li:first-child {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider:hover .arrow {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow-left, .arrow-right {\r\n");
      out.write("\tfont-family: \"SimSun\", \"宋体\";\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.1);\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tmargin-top: -30px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow-left:hover, .arrow-right:hover {\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow-left {\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow-right {\r\n");
      out.write("\tright: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"JQ/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\tvar lenght = $(\".slider li\").length;\r\n");
      out.write("\t\t$(\".arrow-right\").click(function() {\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (count == lenght) {\r\n");
      out.write("\t\t\t\tcount = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".slider li\").eq(count).fadeIn().siblings().fadeOut();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".arrow-left\").click(function() {\r\n");
      out.write("\t\t\tcount--;\r\n");
      out.write("\t\t\tif (count == -1) {\r\n");
      out.write("\t\t\t\tcount = lenght - 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".slider li\").eq(count).fadeIn().siblings().fadeOut();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<table width=\"1347\" border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"10\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"165\"><form id=\"form1\" name=\"form1\" method=\"post\"\r\n");
      out.write("\t\t\t\t\taction=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField\" id=\"imageField\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/logo.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t<td width=\"28\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"22\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"92\">我的亚马逊</td>\r\n");
      out.write("\t\t\t<td width=\"55\">Z秒杀</td>\r\n");
      out.write("\t\t\t<td width=\"59\">礼品卡</td>\r\n");
      out.write("\t\t\t<td width=\"76\">我要开店</td>\r\n");
      out.write("\t\t\t<td width=\"61\">海外购</td>\r\n");
      out.write("\t\t\t<td width=\"46\">帮助</td>\r\n");
      out.write("\t\t\t<td width=\"74\">In English</td>\r\n");
      out.write("\t\t\t<td width=\"143\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"462\"><form id=\"form2\" name=\"form2\" method=\"post\"\r\n");
      out.write("\t\t\t\t\taction=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField2\" id=\"imageField2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/logo1.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table width=\"1347\" border=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"10\" height=\"59\"><p>&nbsp;</p>\r\n");
      out.write("\t\t\t\t\t<p>&nbsp;</p></td>\r\n");
      out.write("\t\t\t\t<td width=\"32\">浏览</td>\r\n");
      out.write("\t\t\t\t<td width=\"129\"><select name=\"select\" id=\"select\">\r\n");
      out.write("\t\t\t\t\t\t<option>全部分类列表</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<td width=\"51\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"84\"><form id=\"form7\" name=\"form7\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\taction=\"\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"select5\" id=\"select5\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>全部分类</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <label for=\"select5\"></label>\r\n");
      out.write("\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td width=\"571\"><form method=\"post\" action=\"myServlet\">\r\n");
      out.write("\t\t\t\t\t\t<label></label> <label></label> <input name=\"context\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"60\" /> <input type=\"submit\" name=\"button\" value=\"搜索\" />\r\n");
      out.write("\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td width=\"44\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"33\">你好</td>\r\n");
      out.write("\t\t\t\t<td width=\"94\"><form id=\"form6\" name=\"form6\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"select4\" id=\"select4\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>我的账户</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <label for=\"select4\"></label>\r\n");
      out.write("\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"><form id=\"form5\" name=\"form5\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"select3\"></label> <input type=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"imageField3\" id=\"imageField3\" src=\"page3/logo2.png\" /><br><br><br>\r\n");
      out.write("\t\t\t\t\t</form><br></td>\r\n");
      out.write("\t\t\t\t<td width=\"87\"><select name=\"select3\" id=\"select3\">\r\n");
      out.write("\t\t\t\t\t\t<option>购物车</option>\r\n");
      out.write("\t\t\t\t</select><br><form action=\"test/Cart\" method=\"get\">id<input name=\"id\"/>name<input name=\"name\"/><input type=\"submit\" value=\"提交\"/><br><br><br></form></td>\r\n");
      out.write("\t\t\t\t<td width=\"102\"><form id=\"form4\" name=\"form4\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\taction=\"\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select2\" id=\"select2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>心愿单</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> <label for=\"select2\"></label>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form><br></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table width=\"1347\" border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"9\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"53\" rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"388\" rowspan=\"3\"><form id=\"form3\" name=\"form3\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField14\" id=\"imageField14\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/logo4.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"85\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"83\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"93\">进口直采</td>\r\n");
      out.write("\t\t\t<td width=\"90\">电子书</td>\r\n");
      out.write("\t\t\t<td width=\"80\">kindle</td>\r\n");
      out.write("\t\t\t<td>阅读软件</td>\r\n");
      out.write("\t\t\t<td>移动客户端</td>\r\n");
      out.write("\t\t\t<td>礼品卡</td>\r\n");
      out.write("\t\t\t<td width=\"101\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td colspan=\"8\" rowspan=\"2\"><input type=\"image\"\r\n");
      out.write("\t\t\t\tname=\"imageField4\" id=\"imageField4\" src=\"page3/logo3.png\" /></td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"3\"><form id=\"form9\" name=\"form9\" method=\"post\"\r\n");
      out.write("\t\t\t\t\taction=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField6\" id=\"imageField6\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/logo5.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td colspan=\"3\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"115\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"147\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"66\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"3\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td height=\"134\" colspan=\"8\">\r\n");
      out.write("\t\t\t  <form id=\"form10\" name=\"form10\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"padding-left:0px;left:0px\"><a href=\"#\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"page3/good.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"padding-left:0px;left:0px\"><a href=\"#\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"page3/2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"padding-left:0px;left:0px\"><a href=\"#\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"page3/3.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"padding-left:0px;left:0px\"><a href=\"#\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"page3/4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"padding-left:0px;left:0px\"><a href=\"#\"><img \r\n");
      out.write("\t\t\t\t\t\t\t        src=\"page3/1.jpg\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t        </a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!--箭头-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"arrow\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"arrow-left\">&lt;</span> <span class=\"arrow-right\">&gt;</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t  </form></td>\r\n");
      out.write("\t\t\t<td rowspan=\"3\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!--<tr>\r\n");
      out.write("\t\t\t<td height=\"29\" colspan=\"8\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\"><input type=\"image\" name=\"imageField9\"\r\n");
      out.write("\t\t\t\tid=\"imageField9\" src=\"page3/logo7.png\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"122\" colspan=\"8\"><form id=\"form16\" name=\"form16\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField8\" id=\"imageField8\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/good.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t</tr>-->\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table width=\"1347\" border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"43\" rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"388\" rowspan=\"3\"><form id=\"form11\" name=\"form11\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\"></form></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">为你推荐</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"66\" rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"205\" rowspan=\"2\"><form id=\"form12\" name=\"form12\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField10\" id=\"imageField10\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/good1.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t<td width=\"208\" rowspan=\"2\"><form id=\"form13\" name=\"form13\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField11\" id=\"imageField11\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/good2.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t<td width=\"207\" rowspan=\"2\"><input type=\"image\"\r\n");
      out.write("\t\t\t\tname=\"imageField12\" id=\"imageField12\" src=\"page3/good3.png\" /></td>\r\n");
      out.write("\t\t\t<td width=\"200\" rowspan=\"2\"><form id=\"form15\" name=\"form15\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" name=\"imageField13\" id=\"imageField13\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"page3/good4.png\" />\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><input type=\"image\" name=\"imageField5\" id=\"imageField5\"\r\n");
      out.write("\t\t\t\tsrc=\"page3/logo8.png\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<form id=\"form14\" name=\"form14\" method=\"post\" action=\"\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<p>&nbsp;</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
