/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2020-02-10 04:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class jobTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>客户管理</title>   \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!-- 导入easyui的资源文件 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<link id=\"themeLink\" rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"login\" class=\"easyui-dialog\" title=\"用户登录\" style=\"width:250px;height:200px\">   \r\n");
      out.write("\t    <form id=\"loginForm\" method=\"post\" >\r\n");
      out.write("\t\t    <table id=\"loginTa\" align=\"center\">\r\n");
      out.write("\t\t\t    <tr><th align=\"right\">账号</th><td><input id=\"username\" type=\"text\" style=\"width:150px\"></td></tr>\r\n");
      out.write("\t\t\t    <tr><th align=\"right\">密码</th><td><input id=\"password\" type=\"password\" style=\"width:150px\"></td></tr>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write(" \t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("\t  \t $(function(){\r\n");
      out.write("\t\t  \t $('#login').dialog({\r\n");
      out.write("                        buttons:[{\r\n");
      out.write("                            iconAlign:'center',\r\n");
      out.write("\t                        text:'注册',\r\n");
      out.write("\t                        handler:function(){\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                       },{\r\n");
      out.write("\t                        iconAlign:'center',\r\n");
      out.write("\t                        text:'登录',\r\n");
      out.write("\t                        handler:function(){\r\n");
      out.write("\t                        }\r\n");
      out.write("                        }]\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("\t\t  \t $('#username').textbox({\r\n");
      out.write("                        iconCls:'icon-man',\r\n");
      out.write("                        iconAlign:'right'\r\n");
      out.write("                    });\r\n");
      out.write("             \r\n");
      out.write("             $('#password').textbox({\r\n");
      out.write("                        iconCls:'icon-lock',\r\n");
      out.write("                        iconAlign:'right'\r\n");
      out.write("                    });\r\n");
      out.write("\t  \t });\r\n");
      out.write("  \t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
