/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2020-03-04 03:47:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class student_005fresume1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>简历填写</title>   \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!-- 导入easyui的资源文件 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("\t<link id=\"themeLink\" rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t<div class=\"easyui-accordion\">\r\n");
      out.write("\t\t<div title=\"基本信息\" style=\"overflow:auto;padding:10px;\">\r\n");
      out.write("\t\t\t<form id=\"editForm1\" method=\"post\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"indiResume_id\">\r\n");
      out.write("\t\t\t\t 姓         名：<input type=\"text\" name=\"indiResume_name\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请输入姓名',required:true\"/><br />\r\n");
      out.write("\t\t\t\t 性         别：<input type=\"radio\" name=\"indiResume_gender\" value=\"男\"/>男\r\n");
      out.write("\t\t  \t\t\t<input type=\"radio\" name=\"indiResume_gender\" value=\"女\"/>女<br />\r\n");
      out.write("\t\t\t\t 年         龄： <input type=\"text\" name=\"indiResume_age\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请输入年龄',required:true\"/><br />\r\n");
      out.write("\t\t\t\t 生         源：<input type=\"text\" name=\"indiResume_res\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请选择生源',required:true\"/><br />\r\n");
      out.write("\t\t\t\t 手         机： <input type=\"text\" name=\"indiResume_telephone\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请输入手机号码',required:true\"/><br />\r\n");
      out.write("\t\t\t\t 自我评价： <input type=\"text\" name=\"indiResume_evaluation\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"prompt:'请输入自我评价',required:false,multiline:true\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width:300px;height:150px\" /><br /><br />\r\n");
      out.write("\t\t\t\t<a id=\"saveBtn1\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\">保存</a>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div title=\"求职意向\" style=\"overflow:auto;padding:10px;\">\r\n");
      out.write("\t\t\t<form id=\"editForm2\" method=\"post\">\r\n");
      out.write("\t\t\t\t工作城市：<input type=\"text\" name=\"indiResume_res\" class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请选择工作城市',required:true\"/><br />\r\n");
      out.write("\t\t\t\t部         门： <input type=\"text\" name=\"indiResume_age\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请输入年龄',required:true\"/><br />\r\n");
      out.write("\t\t\t\t职         位：<input type=\"text\" name=\"indiResume_res\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请选择生源',required:true\"/><br />\r\n");
      out.write("\t\t\t\t期望薪资： <input type=\"text\" name=\"indiResume_telephone\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"prompt:'请输入手机号码',required:true\"/><br />\r\n");
      out.write("\t\t\t\t到岗时间：<input class=\"easyui-datebox\" data-options=\"prompt:'请选择到岗时间'>\r\n");
      out.write("\t\t\t\t<a id=\"saveBtn2\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\">保存</a>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
