/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-07-12 05:48:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import user.*;

public final class visitor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<title>My JSP 'visitor.jsp' starting page</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Meta-Tags -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Meta-Tags -->\r\n");
      out.write("\r\n");
      out.write("<!-- Custom-Stylesheet-Links -->\r\n");
      out.write("<!-- Bootstrap-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- Index-Page-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<!-- Owl-Carousel-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- Date-Picker-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- Chocolat-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/chocolat.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- //Custom-Stylesheet-Links -->\r\n");
      out.write("\r\n");
      out.write("<!-- Fonts -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Montserrat:400,700\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Roboto:100,300,400,500\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\">\r\n");
      out.write("<!-- //Fonts -->\r\n");
      out.write("\r\n");
      out.write("<!-- Font-Awesome-File-Links -->\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- TTF -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/fontawesome-webfont.ttf\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\">\r\n");
      out.write("<!-- //Font-Awesome-File-Links -->\r\n");
      out.write("\r\n");
      out.write("<!-- Supportive-JavaScript -->\r\n");
      out.write("<script src=\"js/modernizr.js\"></script>\r\n");
      out.write("<!-- //Supportive-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div class=\"agileheader\" id=\"agileitshome\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t<div class=\"w3lsnavigation\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-default agilehovereffect wthreehovereffect\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header navbar-left\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"w3_navigation_pos\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\"> <img src=\"images/logo.png\" alt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t\t<h1>ODYSSEY</h1>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse navbar-right\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<nav class=\"link-effect-2\" id=\"link-effect-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#w3lsaboutaits\"><span>ABOUT</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#wthreelocationsaits\"><span>LOCATIONS</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#agilepackagesw3l\"><span>PACKAGES</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#w3portfolioaits\"><span>PORTFOLIO</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#wthreereviews\"><span>REVIEWS</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"scroll\" href=\"#agilecontactw3ls\"><span>CONTACT</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //Navigation -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Slider -->\r\n");
      out.write("\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t<ul class=\"rslides\" id=\"slider\">\r\n");
      out.write("\t\t\t\t<li class=\"first-slide w3ls\"><img src=\"images/slide-1.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreexperience\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"animated-example\" class=\"animated fadeIn\"></div>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"myFunction()\">Reload page</button>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"second-slide aits\"><img src=\"images/slide-2.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreexperience\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"animated-example1\" class=\"animated fadeIn\"></div>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"myFunction()\">Reload page</button>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"third-slide w3-agileits\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/slide-3.jpg\" alt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreexperience\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"animated-example2\" class=\"animated fadeIn\"></div>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"myFunction()\">Reload page</button>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"fourth-slide agileinfo\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/slide-4.jpg\" alt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreexperience\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"animated-example3\" class=\"animated fadeIn\"></div>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"myFunction()\">Reload page</button>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"fifth-slide wthree\"><img src=\"images/slide-5.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"Odyssey\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreexperience\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"animated-example4\" class=\"animated fadeIn\"></div>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"myFunction()\">Reload page</button>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //Slider -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- About -->\r\n");
      out.write("\t<div class=\"w3lsaboutaits\" id=\"w3lsaboutaits\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2>About Our Agency</h2>\r\n");
      out.write("\t\t\t<h4>\"There is no one who loves pain itself, who seeks after it\r\n");
      out.write("\t\t\t\tand wants to have it, simply because it is pain...\"</h4>\r\n");
      out.write("\t\t\t<div class=\"w3lsaboutaits-grids\">\r\n");
      out.write("\t\t\t");
 int j=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /visitor.jsp(161,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /visitor.jsp(161,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(161,4) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /visitor.jsp(161,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /visitor.jsp(161,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(3);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<div class=\"col-md-6 w3lsaboutaits-grid w3lsaboutaits-grid-1\">\r\n");
            out.write("\t\t\t\t\t\t<h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</h3>\r\n");
            out.write("\t\t\t\t\t\t<p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
            out.write("\t\t\t\t\t\t\tdata-target=\"#myModal");
            out.print(j );
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\tREAD MORE<i class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i>\r\n");
            out.write("\t\t\t\t\t\t</button>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<div class=\"modal fade details-modal\" id=\"myModal");
            out.print(j++ );
            out.write("\" tabindex=\"-1\"\r\n");
            out.write("\t\t\t\t\trole=\"dialog\" aria-hidden=\"true\">\r\n");
            out.write("\t\t\t\t\t<div class=\"modal-dialog modal-lg\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\">&times;</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</h4>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" alt=\"Odyssey\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.essay }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Tooltip-Content -->\r\n");
      out.write("\t\t\t<div class=\"tooltip-content\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //Tooltip-Content -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //About -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Details -->\r\n");
      out.write("\t<div class=\"agileinfodetails\" id=\"agileinfodetails\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-12 agileinfodetails-grid agileinfodetails-heading\">\r\n");
      out.write("\t\t\t\t<h3>Experience the Freedom</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"col-md-12 agileinfodetails-grid agileinfodetails-paragraph\">\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed\r\n");
      out.write("\t\t\t\t\tdo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut\r\n");
      out.write("\t\t\t\t\tenim ad minim veniam, quis nostrud exercitation ullamco laboris\r\n");
      out.write("\t\t\t\t\tnisi ut aliquip ex ea commodo consequat.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Details -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Locations -->\r\n");
      out.write("\t<div class=\"wthreelocationsaits\" id=\"wthreelocationsaits\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Locations</h3>\r\n");
      out.write("\t\t\t<section class=\"grid3d vertical\" id=\"grid3d\">\r\n");
      out.write("\t\t\t<div class=\"grid-wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"grid\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<span class=\"loading\"></span> <span class=\"icon close-content\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-times\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Locations -->\r\n");
      out.write("\t<div class=\"tlinks\">\r\n");
      out.write("\t\tCollect from <a href=\"http://www.cssmoban.com/\" title=\"模板之家\">模板之家</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Packages -->\r\n");
      out.write("\t<div class=\"agilepackagesw3l\" id=\"agilepackagesw3l\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h3>Packages</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"owl-demo\" class=\"owl-carousel text-center\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Popup-Box -->\r\n");
      out.write("\t\t\t<div id=\"popup\">\r\n");
      out.write("\t\t\t\t<div id=\"small-dialog\" class=\"mfp-hide agileinfo\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pop_up\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"payment-online-form-left w3-agileits\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"shipping agileits-w3layouts\"></span>Customer\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDetails\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark agileits-w3layouts\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" value=\"First Name\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'First Name';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark agileits\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Last Name\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Last Name';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark agile\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Email\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Email';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Phone';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"paymenthead\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"payment\"></span>Payment Details\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"payment-type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><span class=\"col_checkbox agileits-w3layouts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"3\" class=\"css-checkbox1\" type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"3\" class=\"css-label1\"></label> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"visa agileits-w3layouts\" href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><span class=\"col_checkbox\"> <input id=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"css-checkbox2\" type=\"checkbox\"> <label for=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"css-label2\"></label> <a class=\"paypal w3-agileits\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Card Number\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Card Number';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark w3layouts\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Name on card\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Name on card';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-light hasDatepicker\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"datepicker\" value=\"Expiration Date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Expiration Date';}\"><em\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pay-date\"> </em></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input class=\"text-box-dark agileits-w3layouts\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" value=\"CVV\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'CVV';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"payment-sendbtns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Reset\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" name=\"Process Order\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Process Order\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear agile\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button title=\"Close (Esc)\" type=\"button\"\r\n");
      out.write("\t\t\t\tclass=\"mfp-close w3-agileits\">×</button>\r\n");
      out.write("\t\t\t<!-- //Popup-Box -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Packages -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Portfolio -->\r\n");
      out.write("\t<div class=\"w3portfolioaits\" id=\"w3portfolioaits\">\r\n");
      out.write("\t\t<h3>Portfolio</h3>\r\n");
      out.write("\t\t");

			int i = 1;
		
      out.write("\r\n");
      out.write("\t\t<div class=\"w3portfolioaits-items\">\r\n");
      out.write("\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /visitor.jsp(386,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("list");
      // /visitor.jsp(386,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(386,3) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /visitor.jsp(386,3) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setBegin(150);
      // /visitor.jsp(386,3) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setEnd(161);
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<div\r\n");
            out.write("\t\t\t\t\tclass=\"col-md-3 w3portfolioaits-item w3portfolioaits-item-");
            out.print(i++);
            out.write("\">\r\n");
            out.write("\t\t\t\t\t<a class=\"example-image-link\" href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\tdata-lightbox=\"example-set\" data-title=\"\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"grid\">\r\n");
            out.write("\t\t\t\t\t\t\t<figure class=\"effect-apollo\"> <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\talt=\"Game Robo\"> <figcaption></figcaption> </figure>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f4);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Portfolio -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Reviews -->\r\n");
      out.write("\t<div class=\"wthreereviews\" id=\"wthreereviews\">\r\n");
      out.write("\t\t<main>\r\n");
      out.write("\t\t<div class=\"cd-image-block\">\r\n");
      out.write("\t\t\t<ul class=\"cd-images-list\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"cd-content-block\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"is-selected wthreeli wthreeli-1\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"wthreeli wthreeli-2\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"wthreeli wthreeli-3\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"wthreeli wthreeli-4\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"cd-close\">Close</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"block-navigation\">\r\n");
      out.write("\t\t\t<li><button class=\"cd-prev inactive\">&larr; Prev</button></li>\r\n");
      out.write("\t\t\t<li><button class=\"cd-next\">Next &rarr;</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Reviews -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Contact -->\r\n");
      out.write("\t<div class=\"agilecontactw3ls\" id=\"agilecontactw3ls\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Contact</h3>\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 agilecontactw3ls-grid agilecontactw3ls-grid-1\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" Name=\"First Name\" placeholder=\"FIRST NAME\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"\"> <input type=\"text\" Name=\"Last Name\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"LAST NAME\" required=\"\"> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\t\tName=\"Email\" placeholder=\"EMAIL\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 agilecontactw3ls-grid agilecontactw3ls-grid-2\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"Message\" placeholder=\"MESSAGE\" required></textarea>\r\n");
      out.write("\t\t\t\t\t<div class=\"send-button\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"SEND\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Contact -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Map -->\r\n");
      out.write("\t<div id=\"map\"></div>\r\n");
      out.write("\t<!-- //Map -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Social-Icons -->\r\n");
      out.write("\t<div class=\"agilesocialwthree\">\r\n");
      out.write("\t\t<ul class=\"social-icons\">\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"facebook w3ls\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Facebook Page\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa w3ls fa-facebook-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"twitter w3l\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Twitter Account\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa w3l fa-twitter-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"googleplus w3\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Google Plus Account\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa w3 fa-google-plus-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"instagram wthree\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Instagram Account\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa wthree fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"youtube w3layouts\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Youtube Channel\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa w3layouts fa-youtube-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"pinterest w3layouts\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Pinterest Account\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa w3layouts fa-pinterest-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"tumblr w3layouts\"\r\n");
      out.write("\t\t\t\ttitle=\"Go to Our Tumblr Account\"><i class=\"fa fa-tumblr-square\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Social-Icons -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<div class=\"agilefooterwthree\" id=\"agilefooterwthree\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"agilefooterwthree-grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 agilefooterwthree-grid agilefooterwthree-grid1\">\r\n");
      out.write("\t\t\t\t\t<h4>LINKS</h4>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#agileitshome\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#w3lsaboutaits\"><span>ABOUT</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#wthreelocationsaits\"><span>LOCATIONS</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#agilepackagesw3l\"><span>PACKAGES</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#w3portfolioaits\"><span>PORTFOLIO</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"scroll\" href=\"#wthreereviews\"><span>REVIEWS</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 agilefooterwthree-grid agilefooterwthree-grid2\">\r\n");
      out.write("\t\t\t\t\t<h4>ADDRESS</h4>\r\n");
      out.write("\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>40019 S.p.A</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Parma Via Modena</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Sant'Agata Bolognese</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>BO, Italy</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>+1 (734) 123-4567</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"mail\" href=\"mailto:mail@example.com\">info@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-4 agilefooterwthree-grid agilefooterwthree-grid3 newsletter\">\r\n");
      out.write("\t\t\t\t\t<h4>SUBSCRIBE</h4>\r\n");
      out.write("\t\t\t\t\t<p>Subscribe to our Newsletter</p>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"email aitsw3ls\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Your Email\" required=\"\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" class=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Copyright -->\r\n");
      out.write("\t<div class=\"copyright\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tCopyright &copy; 2017.Company name All rights reserved.More Templates\r\n");
      out.write("\t\t\t<a href=\"http://www.cssmoban.com/\" target=\"_blank\" title=\"模板之家\">模板之家</a>\r\n");
      out.write("\t\t\t- Collect from <a href=\"http://www.cssmoban.com/\" title=\"网页模板\"\r\n");
      out.write("\t\t\t\ttarget=\"_blank\">网页模板</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Copyright -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom-JavaScript-File-Links -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Default-JavaScript -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap-JavaScript -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Responsive-Slider-JavaScript -->\r\n");
      out.write("\t<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#slider\").responsiveSlides({\r\n");
      out.write("\t\t\t\tauto : true,\r\n");
      out.write("\t\t\t\tnav : true,\r\n");
      out.write("\t\t\t\tspeed : 2000,\r\n");
      out.write("\t\t\t\tnamespace : \"callbacks\",\r\n");
      out.write("\t\t\t\tpager : true,\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Responsive-Slider-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Review-Slider-JavaScript -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\t<!-- //Review-Slider-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Tour-Locations-JavaScript -->\r\n");
      out.write("\t<script src=\"js/classie.js\"></script>\r\n");
      out.write("\t<script src=\"js/helper.js\"></script>\r\n");
      out.write("\t<script src=\"js/grid3d.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tnew grid3D(document.getElementById('grid3d'));\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Tour-Locations-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Owl-Carousel-JavaScript -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document)\r\n");
      out.write("\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"#owl-demo, #owl-demo1, #owl-demo2, #owl-demo3, #owl-demo4\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.owlCarousel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoPlay : 4000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titems : 3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titemsDesktop : [ 568, 2 ],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titemsDesktopSmall : [ 414, 1 ]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Owl-Carousel-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Pricing-Popup-Box-JavaScript -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\t\t\ttype : 'inline',\r\n");
      out.write("\t\t\t\tfixedContentPos : false,\r\n");
      out.write("\t\t\t\tfixedBgPos : true,\r\n");
      out.write("\t\t\t\toverflowY : 'auto',\r\n");
      out.write("\t\t\t\tcloseBtnInside : true,\r\n");
      out.write("\t\t\t\tpreloader : false,\r\n");
      out.write("\t\t\t\tmidClick : true,\r\n");
      out.write("\t\t\t\tremovalDelay : 300,\r\n");
      out.write("\t\t\t\tmainClass : 'my-mfp-zoom-in'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Pricing-Popup-Box-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Date-Picker-JavaScript -->\r\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#datepicker,#datepicker1,#datepicker2\").datepicker();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Date-Picker-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Portfolio-Popup-Box-JavaScript -->\r\n");
      out.write("\t<script src=\"js/jquery.chocolat.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('.w3portfolioaits-item a').Chocolat();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Portfolio-Popup-Box-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Smooth-Scrolling-JavaScript -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function(event) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\t\tscrollTop : $(this.hash).offset().top\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Smooth-Scrolling-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Slide-To-Top JavaScript -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID : 'toTop',\r\n");
      out.write("\t\t\t\tcontainerHoverID : 'toTopHover',\r\n");
      out.write("\t\t\t\tscrollSpeed : 100,\r\n");
      out.write("\t\t\t\teasingType : 'linear',\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<a href=\"#agileitshome\" id=\"toTop\" class=\"stuoyal3w scroll stieliga\"\r\n");
      out.write("\t\tstyle=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 0;\">\r\n");
      out.write("\t</span></a>\r\n");
      out.write("\t<!-- //Slide-To-Top JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- //Custom-JavaScript-File-Links -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /visitor.jsp(235,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("list");
    // /visitor.jsp(235,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(235,5) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitor.jsp(235,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(10);
    // /visitor.jsp(235,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(15);
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<figure class=\"col-md-4 effect-zoe\"> <img\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Odyssey\"> <figcaption>\r\n");
          out.write("\t\t\t\t\t\t<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h4>\r\n");
          out.write("\t\t\t\t\t\t</figcaption></figure>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /visitor.jsp(245,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("list");
    // /visitor.jsp(245,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(245,4) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitor.jsp(245,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setBegin(10);
    // /visitor.jsp(245,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setEnd(15);
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"dummy-img dummy-img-1\">\r\n");
          out.write("\t\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Odyssey\">\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<p class=\"dummy-text aitsheadingw3\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t\t<p class=\"dummy-text\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.essay }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /visitor.jsp(274,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("list");
    // /visitor.jsp(274,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(274,4) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitor.jsp(274,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setBegin(108);
    // /visitor.jsp(274,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setEnd(113);
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"item w3-agile\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"agilegrid agilegrid1\">\r\n");
          out.write("\t\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Odyssey\">\r\n");
          out.write("\t\t\t\t\t\t\t<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h4>\r\n");
          out.write("\t\t\t\t\t\t\t<h5>€1300</h5>\r\n");
          out.write("\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li>5 Countries</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li>9 Days, 8 Nights</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li>Choose your Vehicle:</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li>Car, SUV, Bus, RV</li>\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"sign w3-agile text-center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<a class=\"popup-with-zoom-anim\" href=\"#small-dialog\">BOOK\r\n");
          out.write("\t\t\t\t\t\t\t\t\tNOW</a>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f5.setParent(null);
    // /visitor.jsp(411,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setVar("list");
    // /visitor.jsp(411,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/visitor.jsp(411,4) '${list }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitor.jsp(411,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setBegin(50);
    // /visitor.jsp(411,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setEnd(53);
    int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
      if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li class=\"is-selected agiletravelerw3ls agiletravelerw3ls1\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"#0\">\r\n");
          out.write("\t\t\t\t\t\t\t<h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h3> <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Odyssey\">\r\n");
          out.write("\t\t\t\t\t\t\t<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h4>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"wthreeratingaits\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</a></li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f5.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f5);
    }
    return false;
  }
}
